name: weather_and_news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0

  json_annotation: ^4.8.1

  # --- State Management ---
  provider: ^6.1.2

  # --- HTTP & APIs ---
  dio: ^5.5.0+1

  # --- Location & Permissions ---
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # --- Local Storage ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # --- UI Enhancements ---
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  animations: ^2.0.11

  # --- Utility ---
  intl: ^0.19.0
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  assets:
    # Add your assets here, for example:
    # - assets/images/
    # - assets/lottie/