// lib/models/news_article_model.dart

import 'package:json_annotation/json_annotation.dart';

part 'news_article_model.g.dart'; // This line will be generated by build_runner

@JsonSerializable()
class NewsArticle {
  final Source? source;
  final String? author;
  final String? title;
  final String? description;
  final String? url;
  @JsonKey(name: 'urlToImage')
  final String? imageUrl;
  @JsonKey(name: 'publishedAt')
  final DateTime? publishedAt;
  final String? content;

  // Added for bookmarking functionality (not from API, for local state)
  bool isBookmarked;

  NewsArticle({
    this.source,
    this.author,
    this.title,
    this.description,
    this.url,
    this.imageUrl,
    this.publishedAt,
    this.content,
    this.isBookmarked = false, // Default to false
  });

  factory NewsArticle.fromJson(Map<String, dynamic> json) => _$NewsArticleFromJson(json);
  Map<String, dynamic> toJson() => _$NewsArticleToJson(this);

  // Helper for unique identification, useful for bookmarking
  String get uniqueId => url ?? title ?? description ?? publishedAt.toString();
}

@JsonSerializable()
class Source {
  final String? id;
  final String? name;

  Source({this.id, this.name});

  factory Source.fromJson(Map<String, dynamic> json) => _$SourceFromJson(json);
  Map<String, dynamic> toJson() => _$SourceToJson(this);
}

@JsonSerializable()
class NewsApiResponse {
  final String? status;
  final int? totalResults;
  final List<NewsArticle>? articles;

  NewsApiResponse({this.status, this.totalResults, this.articles});

  factory NewsApiResponse.fromJson(Map<String, dynamic> json) => _$NewsApiResponseFromJson(json);
  Map<String, dynamic> toJson() => _$NewsApiResponseToJson(this);
}